name = "softdev"
description = "Serial protocols implemented in software"
version = "1.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = "https://github.com/JeremyGrosser/softdev"
tags = ["embedded", "i2c"]

[[depends-on]]
hal = "^1"
